### ISSUE TITLE
 가게 리스트에서 Footer 접근시 로딩 부분

### ISSUE THREAD

**Issue by younguna** [woowahan-techcamp/2team_Mukkaebie#38]
가게 리스트에서 Footer 접근시

새로운 가게가 로딩 되어서

푸터의 메뉴를 선택하기 힘듬

**Comment by younguna** [comment]
이것은 현 배민의 문제, 배민 먹깨비에서 시도해 보고자 함.

**Comment by heeinso** [comment]
Instagram처럼 무한스크롤 잘 됨
